export const L_MEMBERS = 'Участники';
export const R_VK_ID = 'VK-ID';
export const R_NAME = 'Имя';
export const R_VK_COMMENTID = 'VK-CommentID';
export const R_PROFILE = 'Профиль';
export const R_RATE = 'Баллы';
export const R_COMMENT = 'Комментарий';
export const L_RATE_WORKOUT = 'Начисления: разминки';
export const L_RATE_SPRINT = 'Начисления: спринты';
export const L_RATE_SPAS = 'Начисления: дизайнспас';
export const L_RATE_WITHDRAW = 'Покупки';
export const RUBRICS = [L_RATE_SPAS, L_RATE_WORKOUT, L_RATE_SPRINT, L_RATE_WITHDRAW]